# Generated by Django 6.0.4 on 2026-06-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=255)),
                ('officer_name', models.CharField(max_length=255)),
                ('case_loc', models.CharField(max_length=255)),
                ('case_date', models.DateField()),
                ('case_status', models.CharField(default='Open', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
