# Generated by Django 6.0.4 on 2026-06-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField()),
                ('evidence_name', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='evidence/')),
                ('file_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'evidence',
            },
        ),
    ]
