# Generated by Django 6.0.4 on 2026-06-05 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='case_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='cases.case'),
        ),
    ]
