# Generated by Django 6.0.4 on 2026-06-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_evidence_case_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='case_id',
            new_name='case',
        ),
    ]
